### ISSUE TITLE
table-column-group is missing

### ISSUE THREAD

**Issue by sooheon** [priornix/antizer#10]
In the JSX style API as seen here: https://ant.design/components/table/#components-table-demo-jsx

using a [ant/table-column-group {...}] component says it is undefined.

**Comment by jiacai2050** [comment]
You can just define this yourself like this

```
 (def
  layout-sider
  (reagent.core/adapt-react-class
   (clojure.core/apply
    goog.object/getValueByKeys
    js/antd
    ["Layout" "Sider"])))
```

**Comment by priornix** [comment]
The table-column-group component been added in version 0.3.0.
