### ISSUE TITLE
Update antizer to ant 3.+

### ISSUE THREAD

**Issue by vlaaad** [priornix/antizer#14]
Ant is already at [3.2.0](https://ant.design/changelog#3.2.0) with new components, such as [List](https://ant.design/components/list/) and [Divider](https://ant.design/components/divider/)

**Comment by piotr-yuxuan** [comment]
There is a proposal for that https://github.com/priornix/antizer/pull/16.

**Comment by priornix** [comment]
@vlaaad The library has been updated to ant 3.7.1.
