### ISSUE TITLE
How to put html elements inside the antizer elements

### ISSUE THREAD

**Issue by zcaudate** [priornix/antizer#18]
I'm looking to follow: https://ant.design/components/layout/#components-layout-demo-side

When creating a menu item, if a `:span` element is included, it fails:

    (a/menu-item {:key 1}
        (a/icon {:type "pie-chart"})
         [:span "Option 1"])

whereas, this is fine:

    (a/menu-item {:key 1}
        (a/icon {:type "pie-chart"})
         "Option 1")

is there a way to include the `:span` element?

**Comment by priornix** [comment]
It's actually in the (side-menu) function of the rum example. In your case, you should change the code to:

```
(a/menu-item 
    [:span {:key 1} (a/icon {:type "pie-chart"}) "Option 1"])
```

**Comment by priornix** [comment]
@zcaudate Can we close this ticket?

**Comment by zcaudate** [comment]
yep. thanks for you help.
