### ISSUE TITLE
DatePicker has random characters in the position of "Today"

### ISSUE THREAD

**Issue by narocath** [priornix/antizer#5]
I tried the workaround but still I can't get it to render in english, any ideas?

**Comment by jalehman** [comment]
Have you specified the locale to use using `ant/locale-provider`?

**Comment by narocath** [comment]
yes I did but still no luck :/

**Comment by priornix** [comment]
This issue should be fixed in [0.3.0](https://github.com/priornix/antizer/tree/0.3.0).
